[project]
name = "music-player"
version = "0.1.0"
description = "Web-based music player"
readme = "README.md"
authors = [{ name = "Jason Swift", email = "anemele@outlook.com" }]
requires-python = ">=3.10"
dependencies = [
    "dataclass-binder>=0.3.4",
    "flask>=3.1.0",
    "qrcode>=7.4.2",
    "tinytag>=2.0.0",
]

[project.scripts]
music-player = "music_player.app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
